"""
PDF Report Generator
生成美观的房地产周期分析报告
"""

from typing import Dict, Any, Optional
from datetime import datetime
import io


class PDFReportGenerator:
    """PDF 报告生成器"""
    
    def __init__(self):
        self.page_width = 210  # A4 width in mm
        self.page_height = 297  # A4 height in mm
        self.margin = 20
        
    def generate(self, 
                 city: str,
                 indicators: Dict[str, Any],
                 analysis: str,
                 output_path: Optional[str] = None) -> bytes:
        """
        生成 PDF 报告
        
        Args:
            city: 城市名称
            indicators: 指标数据
            analysis: AI 分析报告
            output_path: 保存路径 (可选)
            
        Returns:
            PDF 字节数据
        """
        try:
            from fpdf import FPDF
        except ImportError:
            return self._generate_simple_pdf(city, indicators, analysis)
        
        pdf = FPDF()
        pdf.add_page()
        
        # 标题
        pdf.set_font('Arial', 'B', 20)
        pdf.cell(0, 15, f'中国房地产周期分析报告', 0, 1, 'C')
        
        # 城市和日期
        pdf.set_font('Arial', 'I', 10)
        pdf.cell(0, 10, f'{city} | {datetime.now().strftime("%Y-%m-%d")}', 0, 1, 'C')
        
        pdf.ln(10)
        
        # 指标数据
        pdf.set_font('Arial', 'B', 14)
        pdf.cell(0, 10, '核心指标', 0, 1)
        pdf.set_font('Arial', '', 11)
        
        aci = indicators.get('aci', 0)
        fpi = indicators.get('fpi', 0)
        lpr = indicators.get('lpr_5y', 0)
        ci = indicators.get('CI', 0)
        
        # ACI
        pdf.set_fill_color(240, 240, 240)
        pdf.cell(60, 8, f'ACI (去化周期)', 1, 0, 'L', 1)
        pdf.cell(40, 8, f'{aci:.1f} 个月', 1, 0, 'C', 1)
        pdf.cell(0, 8, '🟢 正常' if aci < 24 else '🔴 警戒', 1, 1, 'C', 1)
        
        # FPI
        pdf.cell(60, 8, 'FPI (资金链)', 1, 0, 'L', 1)
        pdf.cell(40, 8, f'{fpi:,.0f}', 1, 0, 'C', 1)
        pdf.cell(0, 8, '🟢 安全' if fpi > 0 else '🔴 紧张', 1, 1, 'C', 1)
        
        # LPR
        pdf.cell(60, 8, 'LPR (5年期)', 1, 0, 'L', 1)
        pdf.cell(40, 8, f'{lpr:.2f}%', 1, 0, 'C', 1)
        pdf.cell(0, 8, '正常', 1, 1, 'C', 1)
        
        # CI
        pdf.cell(60, 8, 'CI (复合指数)', 1, 0, 'L', 1)
        pdf.cell(40, 8, f'{ci:.2f}', 1, 0, 'C', 1)
        status = '上行' if ci > 0 else '下行'
        pdf.cell(0, 8, f'📊 {status}', 1, 1, 'C', 1)
        
        pdf.ln(10)
        
        # AI 分析
        pdf.set_font('Arial', 'B', 14)
        pdf.cell(0, 10, 'AI 分析报告', 0, 1)
        pdf.set_font('Arial', '', 10)
        
        # 换行处理
        for line in analysis.split('\n'):
            if line.strip():
                pdf.multi_cell(0, 6, line)
        
        # 页脚
        pdf.set_y(-20)
        pdf.set_font('Arial', 'I', 8)
        pdf.cell(0, 10, 'Generated by China Real Estate Cycle Analyzer', 0, 0, 'C')
        
        # 输出
        if output_path:
            pdf.output(output_path)
        
        return pdf.output(dest='S').encode('latin-1')
    
    def _generate_simple_pdf(self, city: str, indicators: Dict, analysis: str) -> bytes:
        """简单文本 PDF (当 fpdf 不可用时)"""
        
        content = f"""
中国房地产周期分析报告
{city} | {datetime.now().strftime("%Y-%m-%d")}

核心指标:
- ACI (去化周期): {indicators.get('aci', 0):.1f} 个月
- FPI (资金链): {indicators.get('fpi', 0):,.0f}
- LPR (5年期): {indicators.get('lpr_5y', 0):.2f}%
- CI (复合指数): {indicators.get('CI', 0):.2f}

{analysis}

---
Generated by China Real Estate Cycle Analyzer
"""
        return content.encode('utf-8')


def generate_report(city: str, indicators: Dict[str, Any], analysis: str) -> bytes:
    """
    便捷函数：生成报告
    
    Args:
        city: 城市名
        indicators: 指标数据
        analysis: AI 分析结果
        
    Returns:
        PDF 字节数据
    """
    generator = PDFReportGenerator()
    return generator.generate(city, indicators, analysis)


if __name__ == "__main__":
    # 测试
    test_indicators = {
        'aci': 18.5,
        'fpi': 5000,
        'lpr_5y': 4.2,
        'CI': 0.35
    }
    
    test_analysis = """
## 分析结果

1. ACI 为 18.5 个月，处于正常范围
2. FPI 为 5000，资金链充裕
3. LPR 为 4.2%，利率适中
4. CI 为 0.35，周期温和回升

建议：市场平稳，保持关注
"""
    
    pdf_data = generate_report("北京", test_indicators, test_analysis)
    print(f"PDF generated: {len(pdf_data)} bytes")
